version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678Sa
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: inventory-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app               
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev:docker
    environment:
      DB_HOST: host.docker.internal          
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 12345678Sa
      DB_NAME: inventory_db

volumes:
  postgres_data:
